from sqlalchemy import Column, Integer, String, Float
from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()


class Nqhq(Base):
    __tablename__ = 'nqhq'
    index = Column(Integer)
    HQZQDM = Column(String, primary_key=True)
    HQZQJC = Column(String)
    HQZRSP = Column(Float)
    HQJRKP = Column(Float)
    HQZJCJ = Column(Float)
    HQCJSL = Column(Integer)
    HQCJJE = Column(Float)
    HQCJBS = Column(Integer)
    HQZGCJ = Column(Float)
    HQZDCJ = Column(Float)
    HQSYL1 = Column(Float)
    HQSYL2 = Column(Float)
    HQJSD1 = Column(Float)
    HQJSD2 = Column(Float)
    HQHYCC = Column(Integer)
    HQSJW5 = Column(Float)
    HQSSL5 = Column(Integer)
    HQSJW4 = Column(Float)
    HQSSL4 = Column(Integer)
    HQSJW3 = Column(Float)
    HQSSL3 = Column(Integer)
    HQSJW2 = Column(Float)
    HQSSL2 = Column(Integer)
    HQSJW1 = Column(Float)
    HQSSL1 = Column(Integer)
    HQBJW1 = Column(Float)
    HQBSL1 = Column(Integer)
    HQBJW2 = Column(Float)
    HQBSL2 = Column(Integer)
    HQBJW3 = Column(Float)
    HQBSL3 = Column(Integer)
    HQBJW4 = Column(Float)
    HQBSL4 = Column(Integer)
    HQBJW5 = Column(Float)
    HQBSL5 = Column(Integer)
    updated_at = Column(String, primary_key=True)
    api_id = Column(String)
    status = Column(Integer)